import {Theme} from '@/interfaces';
import {colors} from './colors';
import {fontFamilies} from './typography';

export const lightThemes: Theme = {
  transparent: 'transparent',
  primary: colors.black[500],
  secondary: colors.white[700],
  tertiary: colors.black[300],
  error: colors.red[500],
  success: colors.green[500],
  link: colors.green[200],
  fonts: {
    default: {
      bold: fontFamilies.productSans.bold,
      medium: fontFamilies.productSans.medium,
      regular: fontFamilies.productSans.regular,
    },
    primary: {
      bold: fontFamilies.productSans.bold,
      medium: fontFamilies.productSans.medium,
      regular: fontFamilies.productSans.regular,
    },
    secondary: {
      medium: fontFamilies.nunito.semiBold,
    },
    tertiary: {
      regular: fontFamilies.roboto.regular,
    },
  },
  text: {
    default: colors.black[500],
    light: colors.white[500],
    primary: colors.black[600],
    secondary: colors.gray[800],
    tertiary: colors.gray[700],
    quaternary: colors.gray.A300,
    quinary: colors.black[50],
    senary: colors.gray[500],
    septenary: colors.gray.A500,
    link: colors.green[200],
    error: colors.red[500],
    success: colors.green[500],
  },
  background: {
    default: colors.white[500],
    primary: colors.black[300],
    secondary: colors.gray[600],
    tertiary: colors.white.A900,
    quaternary: colors.white[400],
    quinary: colors.white[200],
    input: colors.white[800],
    radio: colors.green[200],
    checkbox: colors.green[500],
    icon: colors.white[500],
  },
  border: {
    default: colors.black.A50,
    primary: colors.gray[50],
    secondary: colors.gray.A50,
    tertiary: colors.white[500],
    quaternary: colors.gray.A500,
    quinary: colors.green[500],
    senary: colors.black[400],
  },
  icon: {
    default: colors.black[400],
    checkbox: colors.gray.A600,
    primary: colors.black[100],
    tertiary: colors.gray[600],
  },
};

export const darkThemes: Theme = {
  transparent: 'transparent',
  primary: colors.white[500],
  secondary: colors.black[800],
  tertiary: colors.white[600],
  error: colors.red[500],
  success: colors.green[500],
  link: colors.green[200],
  fonts: {
    default: {
      bold: fontFamilies.productSans.bold,
      medium: fontFamilies.productSans.medium,
      regular: fontFamilies.productSans.regular,
    },
    primary: {
      bold: fontFamilies.productSans.bold,
      medium: fontFamilies.productSans.medium,
      regular: fontFamilies.productSans.regular,
    },
    secondary: {
      medium: fontFamilies.nunito.semiBold,
    },
    tertiary: {
      regular: fontFamilies.roboto.regular,
    },
  },
  text: {
    default: colors.white[500],
    light: colors.black[500],
    primary: colors.white[600],
    secondary: colors.gray.A100,
    tertiary: colors.gray[200],
    quaternary: colors.gray[200],
    quinary: colors.gray.A200,
    senary: colors.gray.A200,
    septenary: colors.gray.A50,
    link: colors.green[200],
    error: colors.red[500],
    success: colors.green[500],
  },
  background: {
    default: colors.black.A100,
    primary: colors.white[600],
    secondary: colors.black[800],
    tertiary: colors.black[800],
    quaternary: colors.black[800],
    quinary: colors.black[800],
    input: colors.gray.A400,
    radio: colors.green[200],
    checkbox: colors.green[500],
    icon: colors.white[600],
  },
  border: {
    default: colors.white[600],
    primary: colors.gray[200],
    secondary: colors.gray[800],
    tertiary: colors.white[500],
    quaternary: colors.white[300],
    quinary: colors.green[500],
    senary: colors.gray.A50,
  },
  icon: {
    default: colors.gray.A50,
    checkbox: colors.gray[200],
    primary: colors.white[600],
    tertiary: colors.gray[200],
  },
};
